# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearch_and_redis_app', '0002_remove_books_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='Abc', max_length=100),
            preserve_default=False,
        ),
    ]
